---

- hosts: secor-raw
  roles:
    - secor

- hosts: secor-me
  roles:
    - secor

- hosts: cassandra
  roles:
    - cassandra-db-update

- hosts: analytics
  roles:
    - data-products
    - py-scripts

- hosts: api
  roles:
    - api