---

- hosts: secor
  roles:
    - common
    - service

- hosts: analytics
  roles:
    - common
    - service
    - spark

- hosts: cassandra
  roles:
    - cassandra

- hosts: api
  roles:
    - common
    - service