- name: "Install required python packages (debian)"
  become: yes
  action: apt pkg={{ item }} state=present update_cache=yes
  with_items:
    - libffi-dev
    - libssl-dev
    - build-essential
    - python-dev
    - python-pip
    - lzop
  tags:
    - provision-cassandra-backup

- name: "Install Cassandra Snapshotter"
  become: yes
  command: pip install {{item}}
  with_items:
    - cryptography
    - cassandra_snapshotter
  tags:
    - provision-cassandra-backup

- name: copy the cassandra backup script
  template: src=cassandra-backup.j2 dest={{user_home}}/cassandra-backup.sh  mode=755 owner=ec2-user group=ec2-user
  tags:
    - cassandra-backup

- name: cron job to take backups
  cron: name=cassandrabackup minute={{cassandra_backup_cron_min}} hour={{cassandra_backup_cron_hour}}  job="{{analytics_user_home}}/cassandra-backup.sh"
  tags:
    - cassandra-backup