---

- name: Copy Data Products
  copy: src=batch-models-1.0.jar dest={{ analytics.home }}/models
  tags:
    - analytics

- name: Copy Framework Library
  copy: src=analytics-framework-1.0.jar dest={{ analytics.home }}/models
  tags:
    - analytics

- name: Copy Scripts
  template: src={{ item }} dest={{ analytics.home }}/scripts/model-config.sh mode=755 owner=ec2-user group=ec2-user
  with_items: "{{ analytics.scripts }}"
  tags:
    - analytics

- name: Create cron jobs
  cron: name={{ item.key }} minute={{ item.value.minute }} hour={{ item.value.hour }}  job="{{ analytics.home }}/scripts/run-job.sh {{ item.key }}"
  with_dict: "{{ jobs }}"
  tags:
    - analytics