---

- name: Copy Data Products
  copy: src=batch-models-1.0.jar dest={{ analytics.home }}/models
  tags:
    - analytics

- name: Copy Framework Library
  copy: src=analytics-framework-1.0.jar dest={{ analytics.home }}/models
  tags:
    - analytics

- name: Copy Scripts
  template: src={{ item }}.j2 dest={{ analytics.home }}/scripts/{{ item }}.sh mode=755 owner=ec2-user group=ec2-user
  with_items: "{{ analytics.scripts }}"
  tags:
    - analytics

- name: Create cron jobs
  cron: name={{ item.key }} minute={{ item.value.minute }} hour={{ item.value.hour }}  job="{{ analytics.home }}/scripts/run-job.sh {{ item.key }}"
  with_dict: "{{ jobs }}"
  tags:
    - analytics

- name: Create cron jobs
  cron: name={{ item.key }} minute={{ item.value.minute }} hour={{ item.value.hour }}  job="{{ analytics.home }}/scripts/monitor-dp.sh {{ analytics.home }}/scripts/logs/joblog.log"
  with_dict: "{{ monit_jobs }}"
  tags:
    - analytics

- name: Copy GenieSearch
  copy: src=/home/jenkins/workspace/LPA_Deploy_Dataproducts_Dev/platform-scripts/VidyaVani/GenieSearch dest={{ analytics.home }}/scripts
  tags:
    - analytics


- name: Copy VidyavaniCnQ
  copy: src=/home/jenkins/workspace/LPA_Deploy_Dataproducts_Dev/platform-scripts/VidyaVani/VidyavaniCnQ dest={{ analytics.home }}/scripts
  tags:
    - analytics

- name: Copy Data vidyavaani
  copy: src=/home/jenkins/workspace/LPA_Deploy_Dataproducts_Dev/platform-scripts/python/main/vidyavaani dest={{ analytics.home }}/scripts
  tags:
    - analytics

- name: Replace Working directory line
  lineinfile: dest={{ analytics.home }}/scripts/vidyavaani/resources/config.properties regexp='^working_dir=' insertafter="^#working_dir= " line='working_dir=/mnt/data/analytics/content2vec state=present
  tags:
    - analytics


