---
- name: update /etc/environment
  become: yes
  lineinfile: dest=/etc/environment line='aws_key={{ access }}'  state=present insertafter=EOF create=yes

- name: update /etc/environment
  become: yes
  lineinfile: dest=/etc/environment line='aws_secret={{ secret }}' state=present insertafter=EOF create=yes

- name: Create Directory
  become: yes
  file: path=/mnt/data/analytics/models state=directory  

- name: Create Directory
  become: yes
  file: path=/mnt/data/analytics/scripts/logs state=directory  

- name: Set permissions
  become: yes
  file: path=/mnt/data/analytics owner=ec2-user group=ec2-user recurse=yes

- name: Install Java8
  yum: name=java-1.8.0 state=latest
  register: result1

- name: Remove Java7
  yum: name=java-1.7.0-openjdk state=absent  