---
# tasks file for cron-prod
---
# tasks file for cron-dev

- name: copy the scripts
  become: yes
  copy: src=platform-scripts/shell/prod/* dest=/mnt/data/analytics/scripts/

- name: cron1
  become: yes
  cron: name=test1 minute=20 hour=6  job="/mnt/data/analytics/scripts/run-job.sh lpu "

- name: cron2
  become: yes
  cron: name=test2 minute=22 hour=6  job="/mnt/data/analytics/scripts/run-job.sh gls "

- name: cron3
  become: yes
  cron: name=test3 minute=24 hour=6  job="/mnt/data/analytics/scripts/run-job.sh gss"


- name: cron4
  become: yes
  cron: name=test4 minute=26 hour=6  job="/mnt/data/analytics/scripts/run-job.sh ss "

- name: cron5
  become: yes
  cron: name=test5 minute=28 hour=6  job="/mnt/data/analytics/scripts/run-job.sh css "


- name: cron6
  become: yes
  cron: name=test6 minute=45 hour=6  job="/mnt/data/analytics/scripts/run-job.sh dus "


- name: cron7
  become: yes
  cron: name=test7 minute=47 hour=6  job="/mnt/data/analytics/scripts/run-job.sh cus "


- name: cron8
  become: yes
  cron: name=test8 minute=49 hour=6  job="/mnt/data/analytics/scripts/run-job.sh lp "

  
- name: cron9
  become: yes
  cron: name=test9 minute=51 hour=6  job="/mnt/data/analytics/scripts/run-job.sh as "


- name: cron10
  become: yes
  cron: name=test10 minute=53 hour=6  job="/mnt/data/analytics/scripts/run-job.sh las "


- name: cron11
  become: yes
  cron: name=test11 minute=55 hour=6  job="/mnt/data/analytics/scripts/run-job.sh dsu "

 
- name: cron12
  cron: name=test12 minute=57 hour=6  job="/mnt/data/analytics/scripts/run-job.sh lcas "