---
# tasks file for server-prod
- name: normal changes
        become: yes
        lineinfile: dest=/mnt/data/analytics/api/analytics-api-{{ api.version }}/start
                    regexp='execjava$*-cp"$classpath"play.core.server.ProdServerStart$scriptdir'
                    line='java$*-cp"$classpath"-Dconfig.resource=prod.confplay.core.server.ProdServerStart$scriptdir'
                    state=present
 - name: start 
   become: yes
   command: nohup /mnt/data/analytics/api/analytics-api-{{ api.version }}/start &