---
# tasks file for server-prod
- name: normal changes
        become: yes
        lineinfile: dest=/mnt/data/analytics/api/analytics-api-{{ api.version }}/start
                    regexp='exec java $* -cp "$classpath" play.core.server.ProdServerStart $scriptdir'
                    line='exec java $* -cp "$classpath" -Dconfig.resource=prod.conf play.core.server.ProdServerStart $scriptdir'
                    state=present
 - name: start 
   become: yes
   command: nohup /mnt/data/analytics/api/analytics-api-{{ api.version }}/start &