---
#tasks file for run-cql
- name: copy cql
  become: yes
  become_user: ec2-user
  copy: src=data.cql dest=/home/ec2-user

- name: run cql
  become: yes
  become_user: ec2-user
  command: /mnt/data/analytics/apache-cassandra-2.2.6/bin/cqlsh -f /home/ec2-user/data.cql
  register: result

- debug: var=result