---
# tasks file for server
- name: normal changes
   become: yes
   lineinfile: dest=/mnt/data/analytics/api/analytics-api-{{ api.version }}/start
               regexp='play.core.server.NettyServer'
               line='play.core.server.ProdServerStart'
               state=present

- name: start 
  become: yes
  command: nohup /mnt/data/analytics/api/analytics-api-{{ api.version }}/start &