---
# tasks file for start
- name: Stop the Secor service
  become: yes
  script: secor-script.sh stop

- name: Extract the file
  become: yes
  command: tar -zxvf /mnt/secor/deploy/secor-0.2-SNAPSHOT-bin.tar.gz -C /mnt/secor-raw

- name: Stop the Secor service
  become: yes
  script: secor-script.sh start