- hosts: sandbox
  become: yes
  become_method: sudo
  roles:
        - java
        - spark
        - aws-setup
        - cassandra
  tags:
       - sandbox

- hosts: prod-spark
  become: yes
  become_method: sudo
  roles:
        - java
        - spark
        - aws-setup
  tags:
       - prod-spark


#- hosts: prod-cassandra
#  become: yes
#  become_method: sudo
#  roles:
#        - java
#        - aws-setup
#        - prod-cassandra 
#  tags:
#      - prod-cassandra
