- hosts: dev
  become: yes
  become_method: sudo
  vars:
     access: "{{ lookup('file', '/home/jenkins/aws_access') }}"
     secret: "{{ lookup('file', '/home/jenkins/aws_secret') }}"
  roles:
        #- java
        - spark
        - aws-setup
        - cassandra
  tags:
       - dev

- hosts: prod-spark
  become: yes
  become_method: sudo
  vars:
     access: "{{ lookup('file', '/home/jenkins/aws_access') }}"
     secret: "{{ lookup('file', '/home/jenkins/aws_secret') }}"
  roles:
        #- java
        - spark
        - aws-setup
  tags:
       - prod-spark


#- hosts: prod-cassandra
#  become: yes
#  become_method: sudo
#  roles:
#        - java
#        - aws-setup
#        - prod-cassandra 
#  tags:
#      - prod-cassandra
