---
# tasks file for java

- name: add apt repository 
  become: yes
  apt_repository: repo=ppa:webupd8team/java state=present

- name: install & update
  become: yes
  apt: name=oracle-java8-installer state=present update_cache=yes


- name: Update bashrc for JAVA_HOME
  lineinfile: dest={{ ansible_env.HOME }}/.bash_profile line='JAVA_HOME=/usr/lib/jvm/java-8-oracle' owner=ubuntu state=present insertafter=EOF create=True


- name: Export JAVA_HOME
  lineinfile: dest={{ ansible_env.HOME }}/.bash_profile  line='export JAVA_HOME' owner=ubuntu state=present insertafter=EOF create=True

- name: Add JAVA_HOME to the PATH
  become: yes  
  lineinfile: dest={{ ansible_env.HOME }}/.bash_profile line='PATH=$PATH:$JAVA_HOME/bin' owner=ubuntu state=present insertafter=EOF create=True

- name: ADD oracle-java8-set-default
  become: yes
  apt: name=oracle-java8-set-default state=present

